### ISSUE TITLE
Notification counts sometimes become negative

### ISSUE THREAD

**Issue by dktapps** [pmmp/Snooze#1]
```php
<?php

require_once 'vendor/autoload.php';

class TestThread extends \Thread{
	/**
	 * @var \pocketmine\snooze\SleeperNotifier
	 */
	private $notif;
	/** @var int */
	private $sleepTime;

	public $shutdown = false;

	public function __construct(\pocketmine\snooze\SleeperNotifier $notif, int $sleepTime){
		$this->notif = $notif;
		$this->sleepTime = $sleepTime;
	}

	public function run(){
		while(!$this->shutdown){
			if($this->sleepTime > 0){
				usleep($this->sleepTime);
			}
			$this->notif->wakeupSleeper();
		}
	}
}

assert_options(ASSERT_EXCEPTION, true);

$sleeper = new \pocketmine\snooze\SleeperHandler();

$notif1 = new \pocketmine\snooze\SleeperNotifier();
$sleeper->addNotifier($notif1, function(){});
$thread1 = new TestThread($notif1, 10000);

$notif2 = new \pocketmine\snooze\SleeperNotifier();
$sleeper->addNotifier($notif2, function(){});
$thread2 = new TestThread($notif2, 0);

$thread1->start();
$thread2->start();

try{
	while(true){
		$sleeper->sleepUntil(microtime(true) + 0.05);
	}
}catch(\Throwable $e){
	$thread1->shutdown = true;
	$thread1->join();

	$thread2->shutdown = true;
	$thread2->join();
	throw $e;
}
```

This code should run forever, but crashes almost immediately:
```
Fatal error: Uncaught AssertionError: notification count should be >= 0, got -1 in src\ThreadedSleeper.php:66
Stack trace:
#0 src\ThreadedSleeper.php(66): assert(false, 'notification co...')
#1 src\SleeperHandler.php(117): pocketmine\snooze\ThreadedSleeper->clearNotifications(2)
#2 src\SleeperHandler.php(82): pocketmine\snooze\SleeperHandler->processNotifications()
#3 test.php(47): pocketmine\snooze\SleeperHandler->sleepUntil(1526818008.4194)
#4 {main}
  thrown in src\ThreadedSleeper.php on line 66
```

**Comment by dktapps** [comment]
The proposed fix for this did not completely resolve this bug, because it was still possible for races to occur between updating notifCount on ThreadedSleeper and notification on SleeperNotifier. This should correctly be resolved by holding a synchronization lock on ThreadedSleeper when sending a notification to update the notification count _and_ set the notification flag atomically.
